//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Gestion_De_Cours.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Gestion_De_Cours.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Absent.
        /// </summary>
        public static string Absent {
            get {
                return ResourceManager.GetString("Absent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add.
        /// </summary>
        public static string Add {
            get {
                return ResourceManager.GetString("Add", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add Class.
        /// </summary>
        public static string AddClass {
            get {
                return ResourceManager.GetString("AddClass", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add Student :.
        /// </summary>
        public static string AddStudentLB {
            get {
                return ResourceManager.GetString("AddStudentLB", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Adress.
        /// </summary>
        public static string Adress {
            get {
                return ResourceManager.GetString("Adress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Adress 2 :.
        /// </summary>
        public static string Adress2LB {
            get {
                return ResourceManager.GetString("Adress2LB", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Adress :.
        /// </summary>
        public static string AdressLB {
            get {
                return ResourceManager.GetString("AdressLB", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to App File :.
        /// </summary>
        public static string AppFileLB {
            get {
                return ResourceManager.GetString("AppFileLB", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Arabic.
        /// </summary>
        public static string Arabic {
            get {
                return ResourceManager.GetString("Arabic", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Archive.
        /// </summary>
        public static string Archive {
            get {
                return ResourceManager.GetString("Archive", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Attendance.
        /// </summary>
        public static string Attendance {
            get {
                return ResourceManager.GetString("Attendance", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Attendance List.
        /// </summary>
        public static string AttendanceList {
            get {
                return ResourceManager.GetString("AttendanceList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Birth Date.
        /// </summary>
        public static string BirthDate {
            get {
                return ResourceManager.GetString("BirthDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Birth Date :.
        /// </summary>
        public static string BirthDateLB {
            get {
                return ResourceManager.GetString("BirthDateLB", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancel.
        /// </summary>
        public static string Cancel {
            get {
                return ResourceManager.GetString("Cancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CCP.
        /// </summary>
        public static string CCP {
            get {
                return ResourceManager.GetString("CCP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CCP :.
        /// </summary>
        public static string CCPLB {
            get {
                return ResourceManager.GetString("CCPLB", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Charge Student If Absent ?.
        /// </summary>
        public static string ChargeStudent {
            get {
                return ResourceManager.GetString("ChargeStudent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Classes.
        /// </summary>
        public static string Class {
            get {
                return ResourceManager.GetString("Class", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ClassAdd.
        /// </summary>
        public static string ClassAdd {
            get {
                return ResourceManager.GetString("ClassAdd", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Class Info.
        /// </summary>
        public static string ClassInfo {
            get {
                return ResourceManager.GetString("ClassInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Class :.
        /// </summary>
        public static string ClassLB {
            get {
                return ResourceManager.GetString("ClassLB", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Classes List.
        /// </summary>
        public static string ClassList {
            get {
                return ResourceManager.GetString("ClassList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Class Name.
        /// </summary>
        public static string ClassName {
            get {
                return ResourceManager.GetString("ClassName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Class Time.
        /// </summary>
        public static string ClassTime {
            get {
                return ResourceManager.GetString("ClassTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Class Name :.
        /// </summary>
        public static string CNameLB {
            get {
                return ResourceManager.GetString("CNameLB", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Date.
        /// </summary>
        public static string Date {
            get {
                return ResourceManager.GetString("Date", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Date :.
        /// </summary>
        public static string DateLB {
            get {
                return ResourceManager.GetString("DateLB", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Date of Register.
        /// </summary>
        public static string DateOfRegister {
            get {
                return ResourceManager.GetString("DateOfRegister", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Day.
        /// </summary>
        public static string Day {
            get {
                return ResourceManager.GetString("Day", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Day :.
        /// </summary>
        public static string DayLB {
            get {
                return ResourceManager.GetString("DayLB", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete.
        /// </summary>
        public static string Delete {
            get {
                return ResourceManager.GetString("Delete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Discounts.
        /// </summary>
        public static string Discounts {
            get {
                return ResourceManager.GetString("Discounts", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ecole Information.
        /// </summary>
        public static string EcoleInfo {
            get {
                return ResourceManager.GetString("EcoleInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email.
        /// </summary>
        public static string Email {
            get {
                return ResourceManager.GetString("Email", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email :.
        /// </summary>
        public static string EmailLB {
            get {
                return ResourceManager.GetString("EmailLB", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to English.
        /// </summary>
        public static string English {
            get {
                return ResourceManager.GetString("English", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Oops! Something went wrong.
        ///Please contact the technical Support Department..
        /// </summary>
        public static string ExceptionHandle {
            get {
                return ResourceManager.GetString("ExceptionHandle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Export.
        /// </summary>
        public static string Export {
            get {
                return ResourceManager.GetString("Export", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fax :.
        /// </summary>
        public static string FaxLB {
            get {
                return ResourceManager.GetString("FaxLB", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Female.
        /// </summary>
        public static string Female {
            get {
                return ResourceManager.GetString("Female", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to First Name.
        /// </summary>
        public static string FirstName {
            get {
                return ResourceManager.GetString("FirstName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to First Name :.
        /// </summary>
        public static string FirstNameLB {
            get {
                return ResourceManager.GetString("FirstNameLB", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Free Time.
        /// </summary>
        public static string FreeTime {
            get {
                return ResourceManager.GetString("FreeTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Friday.
        /// </summary>
        public static string Friday {
            get {
                return ResourceManager.GetString("Friday", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to From :.
        /// </summary>
        public static string FromLB {
            get {
                return ResourceManager.GetString("FromLB", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Gender.
        /// </summary>
        public static string Gender {
            get {
                return ResourceManager.GetString("Gender", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Gender Group.
        /// </summary>
        public static string GenderGroup {
            get {
                return ResourceManager.GetString("GenderGroup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Gender :.
        /// </summary>
        public static string GenderLB {
            get {
                return ResourceManager.GetString("GenderLB", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to General.
        /// </summary>
        public static string General {
            get {
                return ResourceManager.GetString("General", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Group Name :.
        /// </summary>
        public static string GNameLB {
            get {
                return ResourceManager.GetString("GNameLB", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to GroupChange.
        /// </summary>
        public static string GroupChange {
            get {
                return ResourceManager.GetString("GroupChange", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Group Gender.
        /// </summary>
        public static string GroupGender {
            get {
                return ResourceManager.GetString("GroupGender", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Group :.
        /// </summary>
        public static string GroupLB {
            get {
                return ResourceManager.GetString("GroupLB", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Groups List.
        /// </summary>
        public static string GroupList {
            get {
                return ResourceManager.GetString("GroupList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Group Name.
        /// </summary>
        public static string GroupName {
            get {
                return ResourceManager.GetString("GroupName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Groups.
        /// </summary>
        public static string Groups {
            get {
                return ResourceManager.GetString("Groups", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Have Speciality?.
        /// </summary>
        public static string HasSpec_ {
            get {
                return ResourceManager.GetString("HasSpec?", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Does The Level 
        ///Have Specialities?.
        /// </summary>
        public static string HaveSpec {
            get {
                return ResourceManager.GetString("HaveSpec", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Import.
        /// </summary>
        public static string Import {
            get {
                return ResourceManager.GetString("Import", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Indivisual Classes.
        /// </summary>
        public static string IndivClass {
            get {
                return ResourceManager.GetString("IndivClass", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Inscription Fees.
        /// </summary>
        public static string inscFees {
            get {
                return ResourceManager.GetString("inscFees", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Inscription Fees :.
        /// </summary>
        public static string InscFeesLB {
            get {
                return ResourceManager.GetString("InscFeesLB", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Insert.
        /// </summary>
        public static string Insert {
            get {
                return ResourceManager.GetString("Insert", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Justification.
        /// </summary>
        public static string Justification {
            get {
                return ResourceManager.GetString("Justification", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Language :.
        /// </summary>
        public static string LanguageLB {
            get {
                return ResourceManager.GetString("LanguageLB", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Last Name.
        /// </summary>
        public static string LastName {
            get {
                return ResourceManager.GetString("LastName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Last Name  :.
        /// </summary>
        public static string LastNameLB {
            get {
                return ResourceManager.GetString("LastNameLB", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Level.
        /// </summary>
        public static string Level {
            get {
                return ResourceManager.GetString("Level", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Level :.
        /// </summary>
        public static string LevelLB {
            get {
                return ResourceManager.GetString("LevelLB", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Level Name :.
        /// </summary>
        public static string LevelNameLB {
            get {
                return ResourceManager.GetString("LevelNameLB", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Logo.
        /// </summary>
        public static string Logo {
            get {
                return ResourceManager.GetString("Logo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Main Window.
        /// </summary>
        public static string MainWindow {
            get {
                return ResourceManager.GetString("MainWindow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Male.
        /// </summary>
        public static string Male {
            get {
                return ResourceManager.GetString("Male", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mix.
        /// </summary>
        public static string Mix {
            get {
                return ResourceManager.GetString("Mix", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Monday.
        /// </summary>
        public static string Monday {
            get {
                return ResourceManager.GetString("Monday", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ecole Name AR :.
        /// </summary>
        public static string NameARLB {
            get {
                return ResourceManager.GetString("NameARLB", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ecole Name FR :.
        /// </summary>
        public static string NameFRLB {
            get {
                return ResourceManager.GetString("NameFRLB", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name :.
        /// </summary>
        public static string NameLB {
            get {
                return ResourceManager.GetString("NameLB", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Next.
        /// </summary>
        public static string Next {
            get {
                return ResourceManager.GetString("Next", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No.
        /// </summary>
        public static string No {
            get {
                return ResourceManager.GetString("No", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Note.
        /// </summary>
        public static string Note {
            get {
                return ResourceManager.GetString("Note", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Note :.
        /// </summary>
        public static string NoteLB {
            get {
                return ResourceManager.GetString("NoteLB", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Phone Number 2 :.
        /// </summary>
        public static string Number2LB {
            get {
                return ResourceManager.GetString("Number2LB", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Phone Number :.
        /// </summary>
        public static string NumberLB {
            get {
                return ResourceManager.GetString("NumberLB", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Paid Sessions.
        /// </summary>
        public static string PaidSessions {
            get {
                return ResourceManager.GetString("PaidSessions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Parent Number.
        /// </summary>
        public static string ParentNumber {
            get {
                return ResourceManager.GetString("ParentNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Parent Number :.
        /// </summary>
        public static string ParentNumberLB {
            get {
                return ResourceManager.GetString("ParentNumberLB", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Payment.
        /// </summary>
        public static string Payment {
            get {
                return ResourceManager.GetString("Payment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Payments List.
        /// </summary>
        public static string PaymentList {
            get {
                return ResourceManager.GetString("PaymentList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Per Hour.
        /// </summary>
        public static string PerHour {
            get {
                return ResourceManager.GetString("PerHour", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Per Period.
        /// </summary>
        public static string PerPeriod {
            get {
                return ResourceManager.GetString("PerPeriod", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Per Student.
        /// </summary>
        public static string PerStudent {
            get {
                return ResourceManager.GetString("PerStudent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Phone Number.
        /// </summary>
        public static string PhoneNumber {
            get {
                return ResourceManager.GetString("PhoneNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Phone Number :.
        /// </summary>
        public static string PhoneNumberLB {
            get {
                return ResourceManager.GetString("PhoneNumberLB", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Photos File :.
        /// </summary>
        public static string PhotoFileLB {
            get {
                return ResourceManager.GetString("PhotoFileLB", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Present.
        /// </summary>
        public static string Present {
            get {
                return ResourceManager.GetString("Present", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Price.
        /// </summary>
        public static string Price {
            get {
                return ResourceManager.GetString("Price", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Price :.
        /// </summary>
        public static string PriceLB {
            get {
                return ResourceManager.GetString("PriceLB", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Print.
        /// </summary>
        public static string Print {
            get {
                return ResourceManager.GetString("Print", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reason of Absence.
        /// </summary>
        public static string ReasonofAbsent {
            get {
                return ResourceManager.GetString("ReasonofAbsent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Room.
        /// </summary>
        public static string Room {
            get {
                return ResourceManager.GetString("Room", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Room :.
        /// </summary>
        public static string RoomLB {
            get {
                return ResourceManager.GetString("RoomLB", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Room Name :.
        /// </summary>
        public static string RoomNameLB {
            get {
                return ResourceManager.GetString("RoomNameLB", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Saturday.
        /// </summary>
        public static string Saturday {
            get {
                return ResourceManager.GetString("Saturday", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to School Name :.
        /// </summary>
        public static string SchoolNameLB {
            get {
                return ResourceManager.GetString("SchoolNameLB", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Search :.
        /// </summary>
        public static string SearchLB {
            get {
                return ResourceManager.GetString("SearchLB", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sessions.
        /// </summary>
        public static string Sessions {
            get {
                return ResourceManager.GetString("Sessions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sessions :.
        /// </summary>
        public static string SessionsLB {
            get {
                return ResourceManager.GetString("SessionsLB", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Settings.
        /// </summary>
        public static string Setting {
            get {
                return ResourceManager.GetString("Setting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show Settings.
        /// </summary>
        public static string ShowSettings {
            get {
                return ResourceManager.GetString("ShowSettings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Student Name.
        /// </summary>
        public static string SName {
            get {
                return ResourceManager.GetString("SName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Student Name :.
        /// </summary>
        public static string SNameLB {
            get {
                return ResourceManager.GetString("SNameLB", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Speciality.
        /// </summary>
        public static string Speciality {
            get {
                return ResourceManager.GetString("Speciality", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Speciality :.
        /// </summary>
        public static string SpecialityLB {
            get {
                return ResourceManager.GetString("SpecialityLB", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Speciality Name :.
        /// </summary>
        public static string SpecNameLB {
            get {
                return ResourceManager.GetString("SpecNameLB", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Students.
        /// </summary>
        public static string Student {
            get {
                return ResourceManager.GetString("Student", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Student Add.
        /// </summary>
        public static string StudentAdd {
            get {
                return ResourceManager.GetString("StudentAdd", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Amount of Students.
        /// </summary>
        public static string StudentAmount {
            get {
                return ResourceManager.GetString("StudentAmount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Student Info.
        /// </summary>
        public static string StudentInfo {
            get {
                return ResourceManager.GetString("StudentInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Student :.
        /// </summary>
        public static string StudentLB {
            get {
                return ResourceManager.GetString("StudentLB", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Students List.
        /// </summary>
        public static string StudentList {
            get {
                return ResourceManager.GetString("StudentList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Students.
        /// </summary>
        public static string Students {
            get {
                return ResourceManager.GetString("Students", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Student Total.
        /// </summary>
        public static string StudentTotal {
            get {
                return ResourceManager.GetString("StudentTotal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Studied Sessions.
        /// </summary>
        public static string StudiedSes {
            get {
                return ResourceManager.GetString("StudiedSes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Subject.
        /// </summary>
        public static string Subject {
            get {
                return ResourceManager.GetString("Subject", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Does The Subject 
        ///Already Exists?.
        /// </summary>
        public static string SubjectExist {
            get {
                return ResourceManager.GetString("SubjectExist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Subject :.
        /// </summary>
        public static string SubjectLB {
            get {
                return ResourceManager.GetString("SubjectLB", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Subject Name :.
        /// </summary>
        public static string SubjectNameLB {
            get {
                return ResourceManager.GetString("SubjectNameLB", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sunday.
        /// </summary>
        public static string Sunday {
            get {
                return ResourceManager.GetString("Sunday", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Supposed Total.
        /// </summary>
        public static string SupposedTotal {
            get {
                return ResourceManager.GetString("SupposedTotal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Teachers.
        /// </summary>
        public static string Teacher {
            get {
                return ResourceManager.GetString("Teacher", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Teacher Add.
        /// </summary>
        public static string TeacherAdd {
            get {
                return ResourceManager.GetString("TeacherAdd", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Teacher Info.
        /// </summary>
        public static string TeacherInfo {
            get {
                return ResourceManager.GetString("TeacherInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Teacher :.
        /// </summary>
        public static string TeacherLB {
            get {
                return ResourceManager.GetString("TeacherLB", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Teachers List.
        /// </summary>
        public static string TeacherList {
            get {
                return ResourceManager.GetString("TeacherList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Teacher Name :.
        /// </summary>
        public static string TeacherNameLB {
            get {
                return ResourceManager.GetString("TeacherNameLB", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Teacher Total.
        /// </summary>
        public static string TeacherTotal {
            get {
                return ResourceManager.GetString("TeacherTotal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Teacher Entrance Time.
        /// </summary>
        public static string TEntranceTime {
            get {
                return ResourceManager.GetString("TEntranceTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Text Size :.
        /// </summary>
        public static string TextSizeLB {
            get {
                return ResourceManager.GetString("TextSizeLB", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Thursday.
        /// </summary>
        public static string Thursday {
            get {
                return ResourceManager.GetString("Thursday", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Time.
        /// </summary>
        public static string Time {
            get {
                return ResourceManager.GetString("Time", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Time End.
        /// </summary>
        public static string Time_End {
            get {
                return ResourceManager.GetString("Time End", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Time :.
        /// </summary>
        public static string TimeLB {
            get {
                return ResourceManager.GetString("TimeLB", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Time Start.
        /// </summary>
        public static string TimeStart {
            get {
                return ResourceManager.GetString("TimeStart", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Teacher Name.
        /// </summary>
        public static string TName {
            get {
                return ResourceManager.GetString("TName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to To :.
        /// </summary>
        public static string ToLB {
            get {
                return ResourceManager.GetString("ToLB", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Teacher Payment.
        /// </summary>
        public static string TPayment {
            get {
                return ResourceManager.GetString("TPayment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Teacher Payment Depends on Student ?.
        /// </summary>
        public static string TPaymentDepS {
            get {
                return ResourceManager.GetString("TPaymentDepS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Teacher Salary :.
        /// </summary>
        public static string TPaymentLB {
            get {
                return ResourceManager.GetString("TPaymentLB", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Teacher PaymentMethod.
        /// </summary>
        public static string TPaymentMethod {
            get {
                return ResourceManager.GetString("TPaymentMethod", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Payment Method :.
        /// </summary>
        public static string TPaymentMethodLB {
            get {
                return ResourceManager.GetString("TPaymentMethodLB", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tuesday.
        /// </summary>
        public static string Tuesday {
            get {
                return ResourceManager.GetString("Tuesday", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Type .
        /// </summary>
        public static string Type {
            get {
                return ResourceManager.GetString("Type", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Type :.
        /// </summary>
        public static string TypeLB {
            get {
                return ResourceManager.GetString("TypeLB", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unpaid Sessions.
        /// </summary>
        public static string UnpaidSes {
            get {
                return ResourceManager.GetString("UnpaidSes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Wednesday.
        /// </summary>
        public static string Wednesday {
            get {
                return ResourceManager.GetString("Wednesday", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Workers.
        /// </summary>
        public static string Worker {
            get {
                return ResourceManager.GetString("Worker", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Workers List.
        /// </summary>
        public static string WorkerList {
            get {
                return ResourceManager.GetString("WorkerList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Year.
        /// </summary>
        public static string Year {
            get {
                return ResourceManager.GetString("Year", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Year :.
        /// </summary>
        public static string YearLB {
            get {
                return ResourceManager.GetString("YearLB", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Year Name :.
        /// </summary>
        public static string YearNameLB {
            get {
                return ResourceManager.GetString("YearNameLB", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Yes.
        /// </summary>
        public static string Yes {
            get {
                return ResourceManager.GetString("Yes", resourceCulture);
            }
        }
    }
}
